### ISSUE TITLE
Pulumi overwrite behaviour with BucketObjectV2

### ISSUE THREAD

**Issue by jaketbouma** [jaketbouma/shopkeeper#9]
Discussion on Pulumi slack;
https://pulumi-community.slack.com/archives/CRH5ENVDX/p1747219696984919

>  BucketObjectV2 resource silently overwrites an existing s3 object at the target key. Is this expected?
```
# YAML for a test
...
resources:
  random-data:
    type: aws:s3:BucketObjectv2
    properties:
      bucket: somebucket
      key: /path/to/a/file/that/was/already.there
      content: "Death to whatever was there previously!"
...
```

Update: This is the expected behaviour for S3. We discussed object locks, but these are on version, and not going to meet the need to block overwrites of existing files.
